version: '3'

services:
  dynamodb_local:
    image: amazon/dynamodb-local

    ports:
      - "8000:8000"
    #    command: ["python", "init_dynamodb.py"]
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath /home/dynamodblocal" ]


